group=io.github.mavenindexdoctor
version=0.1.0
# IntelliJ Platform's runIde task is not compatible with configuration-cache serialization
# in the current plugin toolchain.
org.gradle.configuration-cache=false
# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true
