package io.github.mavenindexdoctor.domain;

public enum DiagnosticIssueType {
    LAST_UPDATED,
    INDEX_DIRECTORY_MISSING,
    INDEX_DIRECTORY_EMPTY,
    INDEX_DIRECTORY_UNREADABLE,
    INDEX_DIRECTORY_UNWRITABLE,
    EMPTY_INDEX_FILE,
    ARTIFACT_MISSING_FROM_INDEX,
    SETTINGS_NOT_FOUND,
    SETTINGS_INVALID,
    CENTRAL_MIRROR_MISSING,
    CENTRAL_MIRROR_CONFIGURED,
    MAVEN_OFFLINE_MODE,
    ACTIVE_PROXY,
    INVALID_PROXY
}
